#!/bin/bash

#if ! [[ "$@" == *mvn* ]]; then
#	export m="mvn"
#fi

sudo docker run -u "$(id -u):$(id -g)" \
        -e MAVEN_OPTS="-Dmaven.repo.local=/app/.m2" \
        --entrypoint "mvn" \
        -v "$PWD":/app \
        -w /app maven:3.8.5-openjdk-11 "$@"
